@baseUrl = http://localhost:5000

### GET request to root
GET {{baseUrl}}/



### GET all characters
GET {{baseUrl}}/characters

### GET specific character with id
GET {{baseUrl}}/characters/69dabd112e14b644118cddee

### POST new character
POST {{baseUrl}}/characters
Content-Type: application/json

{
  "name": "snork1",
  "description": "new snork character",
  "species": "Snork",
  "isHibernating": true
}



### GET all artifacts
GET {{baseUrl}}/artifacts


### PATCH an artifact
PATCH {{baseUrl}}/artifacts/69dabd112e14b644118cddf3
Content-Type: application/json

{
  "name": "nowy artefakt",
  "description": "nowy opis artefaktu"
}



### GET all locations
GET {{baseUrl}}/locations

### DELETE a location
DELETE {{baseUrl}}/locations/69dabd112e14b644118cddf5



### GET all relationships including character details using .populate()
GET {{baseUrl}}/relationships